declare const GEMINI_API_KEY: string;
declare const MAX_OUTPUT_TOKEN: string;
declare const TEMPERATURE: string;
declare const TOP_K: string;
declare const TOP_P: string;
declare const CHAT_MAX_OUTPUT_TOKEN: string;
declare const VIDEO_MODEL_NAME: string;
declare const IMAGE_MODEL_NAME: string;
declare const GEMINI_MODEL_NAME: string;
